// Mocks generated by Mockito 5.4.3 from annotations
// in course_test_app/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:yoshua_ui_test/api/endpoint/product/get_product_response.dart' as _i3;
import 'package:yoshua_ui_test/module/home_page/bloc/home_page_bloc.dart' as _i8;
import 'package:yoshua_ui_test/api/api_manager.dart' as _i4;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

class _FakeProductModel_1 extends _i1.SmartFake implements _i3.ProductResponse {
  _FakeProductModel_1(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiManager {
  @override
  _i2.Dio getDio() => (super.noSuchMethod(
    Invocation.method(
      #getDio,
      [],
    ),
    returnValue: _FakeDio_0(
      this,
      Invocation.method(
        #getDio,
        [],
      ),
    ),
    returnValueForMissingStub: _FakeDio_0(
      this,
      Invocation.method(
        #getDio,
        [],
      ),
    ),
  ) as _i2.Dio);

  @override
  _i5.Future<_i3.ProductResponse> product() => (super.noSuchMethod(
    Invocation.method(
      #getProduct,
      [],
    ),
    returnValue: _i5.Future<_i3.ProductResponse>.value(_FakeProductModel_1(
      this,
      Invocation.method(
        #getProduct,
        [],
      ),
    )),
    returnValueForMissingStub:
    _i5.Future<_i3.ProductResponse>.value(_FakeProductModel_1(
      this,
      Invocation.method(
        #getProduct,
        [],
      ),
    )),
  ) as _i5.Future<_i3.ProductResponse>);

  @override
  _i5.Future<_i6.Uint8List> get(
      _i7.Emitter<_i8.HomePageState>? emit,
      String? link,
      int? index,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [
            emit,
            link,
            index,
          ],
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
        returnValueForMissingStub:
        _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
}